#server:
#  address: localhost
#  port: 8080
#spring:
#  thymeleaf:
#    prefix: classpath:templates/
#
#    suffix: .html
#    cache: false
spring:

  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel3.cloudtype.app:30118/devdb
    username: root
    password: 1234

  jpa:
#    database-platform: org.hibernate.dialect.MariaDB53Dialect #5.6 version
    database-platform: org.hibernate.dialect.MariaDB102Dialect  #10.5 version
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
    properties:
      hibernate.format_sql: true


  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: :Kakao
            client_id: 1cfc5abbc1e0dd24af7409e5284da67a
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            redirect-uri: "https://port-0-ezuco-cloudtype-108dypx2ale6e8i6k.sel3.cloudtype.app/login/oauth2/code/{registrationId}"
            #registrationId는 oauth2에서 제공하는 소셜 로그인 이름별 ID를 자동으로 맵핑 해줌  ==kakao
            scope:
            - profile_nickname
            - profile_image
            - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://13.124.151.184:3306/devDB/
#    username: root
#    password: 1234
#
#  jpa:
#    #    database-platform: org.hibernate.dialect.MariaDB53Dialect #5.6 version
#    database-platform: org.hibernate.dialect.MariaDB102Dialect  #10.5 version
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      format_sql: true
#      ddl-auto: update
#    properties:
#      hibernate.format_sql: true


